
<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

# Scalars, Vectors and Matrices 

## The Basics

In [1]:
# Scalar
x=5

In [2]:
# Vector
y= [1,2,3,4]  # row or column

In [3]:
# Matrix
z= [[11, 12, 13],  # row 1
    [21, 22, 23],  # row 2
    [31, 32, 33]]  # row 3
#    c1  c2  c3    -----> Columns
z  

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [7]:
type(z)

list

In [4]:
# Indexing
z[0][0]   # Indexing start at 0

11

In [8]:
import numpy as np

## Scalar

In [6]:
s = 5.25
type(s)

float

In [9]:
s_arr = np.array(5.5)
print(type(s_arr))
print(s_arr.dtype)
print(s_arr.shape)
print(s_arr.ndim)

<class 'numpy.ndarray'>
float64
()
0


In [16]:
s_arr = np.array([5])
print(type(s_arr))
print(s_arr.dtype)
print(s_arr.shape)
print(s_arr.ndim)

<class 'numpy.ndarray'>
int32
(1,)
1


In [11]:
s_arr = np.array([[5]])
print(type(s_arr))
print(s_arr.dtype)
print(s_arr.shape)
print(s_arr.ndim)

<class 'numpy.ndarray'>
int32
(1, 1)
2


## Vector

In [15]:
v = np.array([1,2,3])
print(v)
print(type(v))
print(v.dtype)
print(v.shape)
print(v.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int32
(3,)
1


In [19]:
v = np.array([[1,2,3]], dtype = float)
print(v)
print(type(v))
print(v.dtype)
print(v.shape)
print(v.ndim)

[[1. 2. 3.]]
<class 'numpy.ndarray'>
float64
(1, 3)
2


In [20]:
v2 = v.reshape(3,1)
print(v2)
print(type(v2))
print(v2.dtype)
print(v2.shape)
print(v2.ndim)

[[1.]
 [2.]
 [3.]]
<class 'numpy.ndarray'>
float64
(3, 1)
2


## Matrix

In [21]:
z

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [22]:
m = np.array(z)

In [23]:
print(m)
print(type(m))
print(m.dtype)
print(m.shape)
print(m.ndim)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>
int32
(3, 3)
2


In [24]:
len(v2)

3

In [25]:
len(m)

3

In [26]:
m.shape

(3, 3)

In [27]:
m.shape[0]

3

In [28]:
m.shape[1]

3