
<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

In [1]:
import numpy as np

# Indexing & Slicing

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a[2]            # Select the element at the 2nd index

3

In [4]:
a[0:2]          # Select items at index 0 and 1

array([1, 2])

In [5]:
a[::-1]         # Reversed Array

array([3, 2, 1])

In [6]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
b[1,2]          # Select the element at row 1 column 2 (equivalent to b[1][2])

6.0

In [8]:
b[:2, 1]        # Select items at rows 0 and 1 in column 1

array([2., 5.])

In [9]:
b[:1]           # Select all items at row 0 (equivalent to b[0:1,:])

array([[1.5, 2. , 3. ]])

In [10]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]])
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [11]:
c[1, ...]           # Same as [1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

# Boolean Indexing (with Condition)

In [12]:
a

array([1, 2, 3])

In [25]:
a<2

array([ True, False, False])

In [13]:
a[a<2]

array([1])

In [14]:
a[a%2 ==1]

array([1, 3])

In [15]:
b = np.array([3,1,5])
b

array([3, 1, 5])

In [16]:
np.where(a<b)

(array([0, 2]),)

In [17]:
np.intersect1d(a,b)

array([1, 3])

In [18]:
np.union1d(a,b)

array([1, 2, 3, 5])

# Fancy Indexing

In [19]:
C = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [0,0,0]])

In [23]:
C[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [24]:
C[[0,3]]

array([[1, 2, 3],
       [0, 0, 0]])